---
# tasks file for rpi_install_docker

- name: Install docker from Ubuntu repo
  package:
    name: docker.io
    state: present

- name: Add users to docker group
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
  loop: "{{ docker_users }}"

- name: Install requirements for ansible to manage pip
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_ansible_packages }}"

- name: Install prerequisites for ansible to manage docker
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ pip_packages }}"