---
# defaults file for rpi_install_wireguard
wg_server_interface_addr: 10.0.0.1/24

wg_server_listening_port: "51820" #UDP

wg_server_allowed_addr:
  - addr: 10.0.0.2/32
    public_key: xObbcWZ8WBqk4hrJInEdaCd2Bl4C+cY++JlS3NosrSU=

#Use wg_replace_old_keys var if there are keys in place but you want to overwrite them with new ones
wg_replace_old_keys: false 

