---
# tasks file for rpi_install_wireguard
# Steps
# Enable routing on the RPi
# Install wg
# Do wg configuration

# Do a full repo update

- name: Install wireguard
  package:
    name: wireguard
    state: latest

- name: Generate keys
  include_tasks: genKeys.yml

- name: Create config file
  template:
    src: wg_server_config.j2
    dest: /etc/wireguard/{{ wg_interface_name }}.conf
    mode: 0600



